/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Tab Styles",
  "description": "Change the appearance of the editor tabs to look like other mods.",
  "tags": ["editor", "CattyMod", "Theme"],
  "credits": [
    {
        "name": "Mistium",
        "url": "https://mistium.com"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [
    {
      "url": "mistwarp.css",
      "if": {
        "settings": {
          "tab_style": "mistwarp"
        }
      }
    },
    {
      "url": "turbowarp.css",
      "if": {
        "settings": {
          "tab_style": "turbowarp"
        }
      }
    },
    {
      "url": "scratchbox.css",
      "if": {
        "settings": {
          "tab_style": "scratchbox"
        }
      }
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Tab style",
      "id": "tab_style",
      "type": "select",
      "potentialValues": [
        {
            "name": "MistWarp",
            "id": "mistwarp"
        },
        {
            "name": "TurboWarp",
            "id": "turbowarp"
        },
        {
            "name": "ScratchBox",
            "id": "scratchbox"
        }
      ],
      "default": "MistWarp"
    },
  ],
  "enabledByDefault": false
};
export default manifest;
