name: Reset beta to upstream

on:
  workflow_dispatch:

jobs:
  reset-main:
    if: github.repository == 'cattymod/beta-gui'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset main to upstream
        run: |
          git remote add upstream https://github.com/cattymod/scratch-gui.git
          git fetch upstream main
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
